/**
 * AUTO-GENERATED — DO NOT EDIT MANUALLY
 *
 * Generated by: npm run images:process
 * Source: data/wallpapers-source/
 *
 * Each entry corresponds to a source image that was processed into
 * AVIF + WebP at 1920w, 2560w, and 3840w sizes in public/wallpapers/.
 * 
 * The 2560w size is served by default for optimal quality on modern displays.
 */

export interface GeneratedWallpaper {
  /** Unique ID derived from source filename (kebab-case) */
  id: string;
  /** Human-readable display name (auto-generated from filename) */
  name: string;
  /** Primary AVIF URL (2560w default size) */
  url: string;
  /** WebP fallback URL (2560w default size) */
  urlWebp: string;
}

/**
 * All available wallpapers, dynamically generated from source images.
 * The number of entries here directly determines the number of Premium themes.
 */
export const GENERATED_WALLPAPERS: GeneratedWallpaper[] = [
  {
    id: 'bangkok-night',
    name: 'Bangkok Night',
    url: '/wallpapers/bangkok-night-2560w.avif',
    urlWebp: '/wallpapers/bangkok-night-2560w.webp',
  },
  {
    id: 'bangkok-park',
    name: 'Bangkok Park',
    url: '/wallpapers/bangkok-park-2560w.avif',
    urlWebp: '/wallpapers/bangkok-park-2560w.webp',
  },
  {
    id: 'bangkok-river',
    name: 'Bangkok River',
    url: '/wallpapers/bangkok-river-2560w.avif',
    urlWebp: '/wallpapers/bangkok-river-2560w.webp',
  },
  {
    id: 'bangkok-riverside-night',
    name: 'Bangkok Riverside Night',
    url: '/wallpapers/bangkok-riverside-night-2560w.avif',
    urlWebp: '/wallpapers/bangkok-riverside-night-2560w.webp',
  },
  {
    id: 'bangkok-storm',
    name: 'Bangkok Storm',
    url: '/wallpapers/bangkok-storm-2560w.avif',
    urlWebp: '/wallpapers/bangkok-storm-2560w.webp',
  },
  {
    id: 'bangkok-sunset',
    name: 'Bangkok Sunset',
    url: '/wallpapers/bangkok-sunset-2560w.avif',
    urlWebp: '/wallpapers/bangkok-sunset-2560w.webp',
  },
  {
    id: 'retro-city',
    name: 'Retro City',
    url: '/wallpapers/retro-city-1920w.avif',
    urlWebp: '/wallpapers/retro-city-1920w.webp',
  },
];
